# Generated by Django 5.2.8 on 2025-11-25 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("brasilia", "Brasília"),
                            ("taguatinga", "Taguatinga"),
                            ("ceilandia", "Ceilândia"),
                            ("samambaia", "Samambaia"),
                            ("sobradinho", "Sobradinho"),
                            ("gama", "Gama"),
                            ("planaltina", "Planaltina"),
                            ("aguas_lindas", "Águas Lindas"),
                            ("valparaiso", "Valparaíso de Goiás"),
                            ("novo_gama", "Novo Gama"),
                            ("formosa", "Formosa"),
                        ],
                        max_length=50,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("pf", "Pessoa Física"), ("pj", "Empresa/ONG")],
                        default="pf",
                        max_length=2,
                        verbose_name="Tipo de usuário",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="CPF/CNPJ"
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Razão social"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
