# Generated by Django 6.0 on 2025-12-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, verbose_name='Certificações de reciclagem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome da empresa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Disponível para coletas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_items_capacity',
            field=models.IntegerField(default=0, verbose_name='Capacidade máxima de itens'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de veículo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('doador', 'Doador'), ('beneficiario', 'Beneficiário'), ('pj', 'Empresa/ONG'), ('transportador', 'Transportador/Voluntário'), ('reciclador', 'Parceiro Reciclador'), ('admin', 'Administrador')], default='doador', max_length=20, verbose_name='Tipo de usuário'),
        ),
    ]
