# Generated by Django 6.0 on 2025-12-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_profile_certifications_profile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent_privacy',
            field=models.BooleanField(default=False, verbose_name='Consentimento LGPD'),
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
