# Generated by Django 6.0 on 2025-12-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_profile_consent_privacy_profile_consent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('plano_piloto', 'Plano Piloto (RA I)'), ('gama', 'Gama (RA II)'), ('taguatinga', 'Taguatinga (RA III)'), ('brazlandia', 'Brazlândia (RA IV)'), ('sobradinho', 'Sobradinho (RA V)'), ('planaltina', 'Planaltina (RA VI)'), ('paranoa', 'Paranoá (RA VII)'), ('nucleo_bandeirante', 'Núcleo Bandeirante (RA VIII)'), ('ceilandia', 'Ceilândia (RA IX)'), ('guara', 'Guará (RA X)'), ('cruzeiro', 'Cruzeiro (RA XI)'), ('samambaia', 'Samambaia (RA XII)'), ('santa_maria', 'Santa Maria (RA XIII)'), ('sao_sebastiao', 'São Sebastião (RA XIV)'), ('recanto_das_emas', 'Recanto das Emas (RA XV)'), ('lago_sul', 'Lago Sul (RA XVI)'), ('riacho_fundo', 'Riacho Fundo (RA XVII)'), ('lago_norte', 'Lago Norte (RA XVIII)'), ('candangolandia', 'Candangolândia (RA XIX)'), ('aguas_claras', 'Águas Claras (RA XX)'), ('riacho_fundo_ii', 'Riacho Fundo II (RA XXI)'), ('sudoeste_octogonal', 'Sudoeste/Octogonal (RA XXII)'), ('varjao', 'Varjão (RA XXIII)'), ('park_way', 'Park Way (RA XXIV)'), ('scia', 'SCIA (Setor de Cidades e Indústrias Autárquicas) (RA XXV)'), ('sobradinho_ii', 'Sobradinho II (RA XXVI)'), ('jardim_botanico', 'Jardim Botânico (RA XXVII)'), ('itapoa', 'Itapoã (RA XXVIII)'), ('sia', 'SIA (Setor de Indústrias e Abastecimento) (RA XXIX)'), ('vicente_pires', 'Vicente Pires (RA XXX)'), ('fercal', 'Fercal (RA XXXI)'), ('sol_nascente_por_do_sol', 'Sol Nascente e Pôr do Sol (RA XXXII)'), ('arniqueira', 'Arniqueira (RA XXXIII)'), ('arapoanga', 'Arapoanga (RA XXXIV)'), ('agua_quente', 'Água Quente (RA XXXV)')], max_length=100, verbose_name='Cidade'),
        ),
    ]
