# Generated by Django 5.2.8 on 2025-11-26 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("bom", "Em bom estado"),
                            ("ruim", "Precisa de reparo"),
                        ],
                        default="bom",
                        max_length=10,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contato (opcional)",
                        max_length=254,
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
