# Generated by Django 6.0 on 2025-12-11 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_message_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='delivery_type',
            field=models.CharField(choices=[('coleta', 'Ponto de Coleta'), ('domicilio', 'Retirada em Domicílio')], default='coleta', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço para retirada'),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('em_rota', 'Em Rota'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada'), ('reciclagem', 'Para Reciclagem')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do ponto')),
                ('address', models.CharField(max_length=300, verbose_name='Endereço')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('opening_hours', models.CharField(help_text='ex: 08:00-17:00', max_length=100, verbose_name='Horário de funcionamento')),
                ('capacity', models.IntegerField(default=50, verbose_name='Capacidade em itens')),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_points_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='collection_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='marketplace.collectionpoint'),
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('entregue', 'Entregue')], default='pendente', max_length=20)),
                ('reason', models.TextField(verbose_name='Motivo da solicitação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da rejeição')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='marketplace.donation')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('donation', 'beneficiary')},
            },
        ),
    ]
