# Generated by Django 6.0 on 2025-12-11 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_donation_approved_at_donation_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('atribuida', 'Atribuída'), ('coletada', 'Coletada'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='atribuida', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='deliveries/', verbose_name='Comprovante com foto')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='deliveries/', verbose_name='Assinatura digital')),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('delivery_latitude', models.FloatField(blank=True, null=True)),
                ('delivery_longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='marketplace.donation')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
