# Generated by Django 6.0 on 2025-12-11 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('address', models.CharField(max_length=300, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contato')),
                ('environmental_license', models.CharField(blank=True, max_length=100, verbose_name='Licença ambiental')),
                ('certifications', models.TextField(blank=True, help_text='ISO, etc.', verbose_name='Certificações')),
                ('accepts_electronics', models.BooleanField(default=True, verbose_name='Aceita eletrônicos')),
                ('accepts_batteries', models.BooleanField(default=True, verbose_name='Aceita baterias')),
                ('accepts_metals', models.BooleanField(default=True, verbose_name='Aceita metais')),
                ('max_monthly_capacity_kg', models.IntegerField(default=1000, verbose_name='Capacidade mensal (kg)')),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=100, verbose_name='Pessoa de contato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parceiro de Reciclagem',
                'verbose_name_plural': 'Parceiros de Reciclagem',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='RecyclingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True, verbose_name='Código do lote')),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('coletado', 'Coletado'), ('enviado', 'Enviado ao reciclador'), ('processado', 'Processado'), ('certificado', 'Certificado')], default='criado', max_length=20)),
                ('estimated_weight_kg', models.FloatField(default=0, verbose_name='Peso estimado (kg)')),
                ('actual_weight_kg', models.FloatField(blank=True, null=True, verbose_name='Peso real (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de coleta')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de envio')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de processamento')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Número do certificado')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='recycling_certificates/', verbose_name='Arquivo do certificado')),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de emissão do certificado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_batches_created', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='recycling_batches', to='marketplace.donation')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_batches_processed', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='marketplace.recyclingpartner')),
            ],
            options={
                'verbose_name': 'Lote de Reciclagem',
                'verbose_name_plural': 'Lotes de Reciclagem',
                'ordering': ['-created_at'],
            },
        ),
    ]
