# Generated by Django 6.0 on 2025-12-11 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_recyclingpartner_recyclingbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='beneficiary',
            field=models.ForeignKey(blank=True, help_text='Beneficiário que vai receber a doação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
