# Generated by Django 6.0 on 2025-12-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_donation_beneficiary'),
    ]

    operations = [
    ]
